# Generated by Django 5.0 on 2023-12-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0003_tipo_gasto_tipo_ingreso_gastos_ingresos'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='total_gasto',
            field=models.FloatField(default=0.0),
        ),
    ]
