# Generated by Django 5.0 on 2023-12-23 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0005_alter_gastos_fecha_registro_alter_gastos_tipogasto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastos',
            name='idgasto',
        ),
        migrations.RemoveField(
            model_name='ingresos',
            name='idingreso',
        ),
        migrations.RemoveField(
            model_name='tipo_gasto',
            name='idTipoGasto',
        ),
        migrations.RemoveField(
            model_name='tipo_ingreso',
            name='idTipoIngreso',
        ),
        migrations.AddField(
            model_name='gastos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresos',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_gasto',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo_ingreso',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
