# Generated by Django 5.0 on 2023-12-23 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_module', '0006_remove_gastos_idgasto_remove_ingresos_idingreso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresos',
            name='total_ingreso',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingresos',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
